name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller selenium undetected-chromedriver faker

    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile --name DarkTokenizer darkgmailtokenizer_gui.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: DarkTokenizer
        path: dist/DarkTokenizer.exe
